INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (123,'Simon ',' Bolivar', '22',  'Kra11#9-56', '7702291', 'Cali'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (456,'Mark ',' Zuckerberg', '20',   'Cll 21#95-52', '+57-315291', 'Medellin'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (789,'Drew ',' Barrymore', '28',  'Kra52#65-05', '3125359456', 'Cali'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (741,'Larry ',' Page', '22',  'Cll 05#52-95', '7872296', 'Tunja'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (147,'Tom ',' Delonge', '15',  'Cll 52#65-56', '7992293', 'Medellin'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (852,'Simon ',' Bolivar', '42',   'Kra 21#65-52', '982295', 'Bogota'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (258,'Mark ',' Hoppus', '52',  'Cll 11#95-9', '8952294', 'Bogota');
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (963,'Britney','  Spears', '28',  'Cll 05#52-56', '7705295', 'Tunja');
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (369,'John ',' Forbes Nash', '62',   'Kra 21#05-56', '776622966', 'Cali'); 
INSERT INTO `biblioteca`.`usuario` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (159,'Tom ',' Delonge', '72',  'Kra05#65-05', '6702293','Medellin');
INSERT INTO `MYDB`.`PERSONA` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (753,'Sergey','  Brin', '32',  'Cll 11#65-11', '9702299', 'Medellin'); 
INSERT INTO `MYDB`.`PERSONA` (`IDPERSONA`, `NOMBRE`, `APELLIDO`, `EDAD`, `DIRECCIÓN`, `TELEFONO`, `CIUDAD`) VALUES (153,'Emma ',' Watson', '32',   'Kra 9#9-95', '31569638', 'Tunja'); 
