INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(1,'Coca-Cola 2L',2400); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(2,'Doritos',1000);
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(3,'Salchicha',3600); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(4,'Pan',500); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(5,'Queso',1000); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(6,'Sandia',8000); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(7,'Leche 1L',4563); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(8,'Atun',1800); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(9,'Pescado',7856); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(10,'Cicla Estatica',1800); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(11,'Camiseta',12000); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(12,'Blue-Jean',7800); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(13,'Papaya',1400); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(14,'Agua en Bolsa',1800); 
 INSERT INTO `MYDB`.`PRODUCTO` (`IDPRODUCTO`, `NOMBRE`, `PRECIO`) VALUES(15,'Red Bull',1200);


